### ISSUE TITLE
Display Teams on Website

### ISSUE THREAD

**Issue by jmstefans** [jmstefans/FlavorOfTheMonth#17]
Need to come up with an idea for what to show/display in the Teams section when someone has filtered each class and spec dropdown leaving only gender, race, and faction differences. I'm thinking we could show those differences somehow and also display the actual player's names with a link to their armories.

**Comment by jmstefans** [comment]
This involves all of the graphics for faction, spec, class, gender, and race.

**Comment by jmstefans** [comment]
Compute hash of team comp to increment counters for aggregate

**Comment by AndrewNoyes** [comment]
Issue complete(ish), closing.
