### ISSUE TITLE
implement get methods for accessing team data - dal

### ISSUE THREAD

**Issue by AndrewNoyes** [jmstefans/FlavorOfTheMonth#23]

**Comment by jmstefans** [comment]
Do we still need this? I've just been using the stored procedure SP_GetAllTeamsOverTheLastMonthByClassCompositionThenOrderThemByMostPopular. I also noticed we already have a GetTeamByTeamId() in the DAL. What specific methods did you want to add in here?

**Comment by AndrewNoyes** [comment]
nah, it was meant to just be an issue for the implementation of the website and data

**Comment by AndrewNoyes** [comment]
closing, too vague
