### ISSUE TITLE
setup multiple regions and brackets wow api

### ISSUE THREAD

**Issue by AndrewNoyes** [jmstefans/FlavorOfTheMonth#28]

**Comment by AndrewNoyes** [comment]
reopening, need to fix with multiple brackets being queried across multiple threads

**Comment by AndrewNoyes** [comment]
closing - regions and brackets are implemented!

**Comment by jmstefans** [comment]
YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
