### ISSUE TITLE
cluster on modified date/time (proposed)

### ISSUE THREAD

**Issue by AndrewNoyes** [jmstefans/FlavorOfTheMonth#29]
Adding the datetime property to the clustering may improve the accuracy. Might be worth testing pre-launch - adding label for now.

* need to normalize data first
* use the mean of squared error?

**Comment by jmstefans** [comment]
Probably a good thing to do.

**Comment by AndrewNoyes** [comment]
Closing for now. I don't think date would be useful. Right now, the only team members clustered are the ones received from the same API call, so they'll always have the same modified date.
