### ISSUE TITLE
pvpstats, character, team tables

### ISSUE THREAD

**Issue by AndrewNoyes** [jmstefans/FlavorOfTheMonth#3]
PvpStats: 
 add another job to pull the current pvp stats from api and update the db
this doesn't need to be as often as the api requests for clustering, maybe every 30 min would be appropriate, or if a character's rating changes then update the db with current value

 Character: 
  add a db table for character link it to the pvpstats table
 this may require a separate api call to get the character's profile

 Team:  add a db table for team, update the team table every cluster run with the clustered team

**Comment by jmstefans** [comment]
A character table already exists but it's only CharacterId, name, server, and the 3 modified columns. So it could be changed to reflect the explorer's model.

**Comment by jmstefans** [comment]
Closing as these are all done except will open another issue for updating pvpstats with current rating on api call.
